context:
  version: "54"

package:
  name: awkward-cpp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/awkward-cpp/awkward_cpp-${{ version }}.tar.gz
  sha256: c957b2804be6a7ba28b996c4cb00b744624d4b78de8461ef7788f8f8e502828e

build:
  number: 0
  variant:
    use_keys:
      - x86_64_microarch_level
    down_prioritize_variant: ${{ 0 if (x86_64_microarch_level | default(1)) == 1 else 1 }}
  script:
    # Intentionally skip win for the time being
    - if: unix
      then: export CMAKE_GENERATOR=Ninja
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    # c.f. https://github.com/conda-forge/awkward-cpp-feedstock/pull/67#issuecomment-3073170539
    - if: unix and x86_64
      then: x86_64-microarch-level ${{ '==' ~ x86_64_microarch_level if x86_64_microarch_level else "*" }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: ninja
  host:
    - python
    - pip
    - scikit-build-core >=0.11.0
    - pybind11
  run:
    - python
    - numpy >=1.21.3

tests:
  - python:
      imports:
        - awkward_cpp
      pip_check: true

about:
  homepage: https://github.com/scikit-hep/awkward
  repository: https://github.com/scikit-hep/awkward
  documentation: https://awkward-array.org/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt

extra:
  recipe-maintainers:
    - henryiii
    - conda-forge/awkward
    - conda-forge/scikit-hep
